name: music_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.4
  provider: ^6.0.5
  sizer: ^2.0.15
  salomon_bottom_bar: ^3.3.2
  marquee: ^2.2.3
  card_swiper: ^3.0.1
  dynamic_height_grid_view: ^0.0.4
  audio_video_progress_bar: ^1.0.1
  dropdown_button2: ^2.1.4
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  permission_handler: ^11.3.1
  on_audio_query: ^2.9.0
  shared_preferences: ^2.2.3
  just_audio: ^0.9.36
  searchbar_animation: ^0.0.4
  bottom_sheet: ^4.0.2
  share_plus: ^7.2.2  
  flutter_staggered_grid_view: ^0.7.0
  mesh_gradient: ^1.3.4
  just_audio_background: ^0.0.1-beta.12
dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:

 
  uses-material-design: true


  assets:
    - images/
 
  fonts:
    - family: elYazisi
      fonts:
        - asset: fonts/PlaypenSans-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: musikCardYazi
      fonts:
        - asset: fonts/RobotoSlab-VariableFont_wght.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
